version: '3.8'

services:
  game_app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    env_file:
      - .env
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
